<Project Sdk="Meadow.Sdk/1.1.0">
  <PropertyGroup>
    <Company>Wilderness Labs, Inc</Company>
    <Authors>Wilderness Labs, Inc</Authors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>App</AssemblyName>
    <Configurations>Release;Debug</Configurations>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Meadow" Version="*" />
  </ItemGroup>
</Project>
