<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Authors>Wilderness Labs, Inc</Authors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <LangVersion>preview</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>Meadow.Windows</AssemblyName>
    <Company>Wilderness Labs, Inc</Company>
    <PackageProjectUrl>http://developer.wildernesslabs.co/Meadow/</PackageProjectUrl>
    <PackageId>Meadow.Windows</PackageId>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/WildernessLabs/Meadow.Core</RepositoryUrl>
    <PackageTags>Meadow</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Description>An implementation of the Meadow software stack for Windows targets</Description>
  </PropertyGroup>
    
  <ItemGroup>
    <PackageReference Include="ManagedNativeWifi" />
    <PackageReference Include="NetEscapades.Configuration.Yaml" />
    <PackageReference Include="Silk.NET" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="System.IO.Hashing" />
    <PackageReference Include="System.IO.Ports" />
    <PackageReference Include="System.Net.WebSockets" />
    <PackageReference Include="System.Text.Json" />
    <ProjectReference Include="..\..\..\..\..\Meadow.Foundation\Source\Meadow.Foundation.Peripherals\Displays.Silk\Driver\Displays.Silk.csproj" />
    <ProjectReference Include="..\..\..\Meadow.Core\Meadow.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\icon.png" Link="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
