<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Company>Wilderness Labs, Inc</Company>
    <Authors>Wilderness Labs, Inc</Authors>
    <PackageProjectUrl>http://developer.wildernesslabs.co/Meadow/</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>Meadow.Desktop</AssemblyName>
    <PackageId>Meadow.Desktop</PackageId>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Cross-platform desktop .NET libraries for Wilderness Labs Meadow</Description>
    <PackageIcon>icon.png</PackageIcon>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\..\icon.png" Link="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
    
  <ItemGroup>
    <PackageReference Include="ManagedNativeWifi" />
    <PackageReference Include="NetEscapades.Configuration.Yaml" />
    <PackageReference Include="Silk.NET" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="System.IO.Hashing" />
    <PackageReference Include="System.IO.Ports" />
    <PackageReference Include="System.Net.WebSockets" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\Meadow.Foundation\Source\Meadow.Foundation.Core\Meadow.Foundation.Core.csproj" />
    <ProjectReference Include="..\..\linux\Meadow.Linux\Meadow.Linux.csproj" />
    <ProjectReference Include="..\..\mac\Meadow.Mac\Meadow.Mac.csproj" />
    <ProjectReference Include="..\..\windows\Meadow.Windows\Meadow.Windows.csproj" />
  </ItemGroup>
</Project>
