<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Company>Wilderness Labs, Inc</Company>
    <Authors>Wilderness Labs, Inc</Authors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <LangVersion>preview</LangVersion>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>App</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Meadow.Simulation\Meadow.Simulation.csproj" />
  </ItemGroup>
</Project>
