using System;
using System.Collections.Generic;
using System.IO;

namespace Meadow;

public partial class F7PlatformOS : IPlatformOS
{
    /// <summary>
    /// The file name used for passing Platform OS messages to the Meadow stack
    /// </summary>
    public const string OsMessageFile = "meadow.log";

    /// <summary>
    /// Retrieves any messages generated by the Meadow host OS prior to starting the Meadow stack
    /// </summary>
    /// <returns></returns>
    public IEnumerable<PlatformOsMessage>? GetStartupMessages()
    {
        var list = new List<PlatformOsMessage>();

        // On the F7 platforms, Nuttx passes messages via a file named `meadow.log` which is tilde-delimited
        // sample data
        /*
        I~2023-02-21T09:05:29Z~Logging started
        E~2023-02-21T09:05:30Z~CONFIG: Load: libyaml: did not find expected key
        E~2023-02-21T09:05:30Z~CONFIG: Load: Backtrace:
        E~2023-02-21T09:05:30Z~CONFIG:   in mapping field: Interfaces
        E~2023-02-21T09:05:30Z~CONFIG:   in mapping field: Network
        E~2023-02-21T09:05:30Z~Error processing config file, using default config
        */

        var path = Path.Combine(FileSystemRoot, OsMessageFile);

        if (File.Exists(path))
        {
            try
            {
                var contents = File.ReadAllText(path);
                var lines = contents.Split(new char[] { '\n' }, StringSplitOptions.RemoveEmptyEntries);

                foreach (var line in lines)
                {
                    var fields = line.Split(new char[] { '~' }, StringSplitOptions.RemoveEmptyEntries);

                    if (fields.Length == 3)
                    {
                        var priority = fields[0] switch
                        {
                            "E" => MessagePriority.Error,
                            "W" => MessagePriority.Warning,
                            "I" => MessagePriority.Information,
                            _ => MessagePriority.Debug
                        };

                        var ts = DateTime.ParseExact(fields[1], "yyyy-MM-ddTHH:mm:ssZ", null);

                        list.Add(new PlatformOsMessage
                        {
                            Priority = priority,
                            Timestamp = ts,
                            Message = fields[2]
                        });
                    }
                }
            }
            catch (Exception ex)
            {
                Resolver.Log.Warn($"Unable to parse Platform OS messages from '{path}': {ex.Message}");
            }
        }

        return list;
    }
}
